spring.application.name=member-service
server.port=8101
management.endpoints.web.exposure.include=health,info


spring.datasource.url=jdbc:h2:file:./.data/member-service
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.locations=classpath:db/migration
clients.notification.url=http://localhost:8109
member.verification-ttl=PT24H
member.session-ttl=P14D
