spring.application.name=order-service
server.port=8108
management.endpoints.web.exposure.include=health,info
clients.member.url=http://localhost:8101
clients.catalog.url=http://localhost:8102
clients.inventory.url=http://localhost:8104
clients.cart.url=http://localhost:8105
clients.payment.url=http://localhost:8106
clients.shipping.url=http://localhost:8107
clients.notification.url=http://localhost:8109

spring.datasource.url=jdbc:h2:file:./.data/order-service
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.locations=classpath:db/migration
