spring.config.import=classpath:application-shared.properties
spring.application.name=order-consumer
server.port=8127

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:order-shipment-events}
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.impati.commerce.common.ApiContracts$ShipmentEventMessage
spring.kafka.consumer.properties.spring.json.trusted.packages=com.impati.commerce.common
