pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'impati-commerce'

include 'libs:common-contracts'
include 'libs:common-http'
include 'libs:test-database'
include 'apps:api-gateway'
include 'apps:member-service'
include 'apps:display-service'
include 'apps:catalog-service'
include 'apps:inventory-service'
include 'apps:cart-service'
include 'apps:order-service:core'
include 'apps:order-service:persistence'
include 'apps:order-service:client-core'
include 'apps:order-service:client-member'
include 'apps:order-service:client-cart'
include 'apps:order-service:client-catalog'
include 'apps:order-service:client-inventory'
include 'apps:order-service:client-payment'
include 'apps:order-service:client-shipping'
include 'apps:order-service:client-notification'
include 'apps:order-service:publisher-notification'
include 'apps:order-service:api'
include 'apps:order-service:worker'
include 'apps:payment-service'
include 'apps:shipping-service'
include 'apps:notification-service:core'
include 'apps:notification-service:persistence'
include 'apps:notification-service:mail'
include 'apps:notification-service:api'
include 'apps:notification-service:worker'

