create table return_progress (
    id                    varchar(64) primary key,
    order_id              varchar(64) not null,
    member_id             varchar(64) not null,
    reason                varchar(32) not null,
    description           varchar(500),
    aware_date            date,
    refund_amount         bigint not null,
    refund_currency       varchar(8) not null,
    status                varchar(32) not null,
    refund_status         varchar(24) not null,
    inventory_status      varchar(24) not null,
    return_shipment_id    varchar(64),
    disposition           varchar(24),
    item_condition        varchar(64),
    pickup_address_id     varchar(64),
    pickup_alias          varchar(64),
    pickup_recipient      varchar(128) not null,
    pickup_phone          varchar(64),
    pickup_line1          varchar(255) not null,
    pickup_city           varchar(128),
    pickup_postal_code    varchar(32),
    pickup_default_address boolean not null,
    created_at            datetime(6) not null,
    received_at           datetime(6),
    inspection_due_at     datetime(6),
    active_order_id varchar(64)
        generated always as (case when status <> 'WITHDRAWN' then order_id else null end) stored,
    unique key uq_return_progress_active_order (active_order_id),
    key idx_return_progress_recovery (status, refund_status, inventory_status, inspection_due_at),
    constraint fk_return_progress_order foreign key (order_id) references orders (id)
);
