spring.application.name=notification-service
server.port=8109
management.endpoints.web.exposure.include=health,info


spring.datasource.url=jdbc:h2:file:./.data/notification-service
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.locations=classpath:db/migration
