plugins {
    id 'java-library'
}

dependencies {
    api project(':libs:common-contracts')
    api 'org.springframework.boot:spring-boot-autoconfigure:3.2.3'
    api 'org.springframework:spring-web:6.1.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.4'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}
