-- 주문 상태 전이를 사건으로 커밋한다 (BL-0052, ADR-0012).
--
-- 주문 행 갱신과 같은 트랜잭션에서 커밋되므로 "결제됐는데 알릴 의도가 없다"가 생기지 않고,
-- 커밋된 사건은 프로세스가 죽어도 남으므로 재시도가 재시작을 넘어 이어진다.
--
-- 여기 적히는 것은 지시가 아니라 사실이다. "이 문구로 알려라"가 아니라 "주문이 결제됐다"이며,
-- 소비자별 표현(subject/body)은 발행 직전에 만든다. 사실에 한 소비자의 표현을 박으면 두 번째
-- 소비자가 쓸 수 없다.
create table order_events (
    id             varchar(64)   primary key,
    seq            bigint        generated by default as identity,

    -- 상태 전이의 종류. status를 바꾸는 전이만 사건이 된다 — 협력자 id를 적거나 운영 플래그를
    -- 토글하는 것은 saga 내부 단계이고, 사건으로 노출하면 그 실행 순서가 계약이 된다.
    type           varchar(40)   not null,

    order_id       varchar(64)   not null,
    member_id      varchar(64)   not null,

    -- 사건별 사실. JSON 한 칸인 이유는 "새 전이 = 새 사건"이라는 규칙 때문이다. 컬럼으로 두면
    -- 사건 하나 추가가 마이그레이션 하나가 되어 그 규칙을 쓸 수 없게 된다.
    payload        varchar(2000) not null,

    -- 발행 상태. 소비자별로 나누지 않는다 — 팬아웃은 브로커의 일이고, 여기서 확인할 것은
    -- "발행됐다" 하나다. 소비자별 전달 테이블은 브로커가 할 일을 DB로 흉내 내는 것이다.
    publish_status varchar(16)   not null,
    attempts       int           not null default 0,
    last_error     varchar(500),

    -- 다음 시도 시각. 한 문장으로 묶음을 집을 때 이 값을 미래로 밀어 점유한다 (ADR-0011과 같은
    -- 방식). 배타성·백오프·크래시 자기치유가 이 컬럼 하나에서 나온다 — 점유가 시각을 미리
    -- 밀어두므로 실패 경로에 쓰기가 없어도 최소 간격 안에는 다시 집히지 않는다.
    --
    -- null은 "지금 발행할 수 있다"는 뜻이며 기록 시점의 기본값이다.
    next_attempt_after timestamp with time zone,

    -- 이 주기가 집은 묶음의 식별자. 집은 뒤 이 값으로 다시 읽는다.
    tx_id          varchar(64),

    constraint fk_order_events_order foreign key (order_id) references orders (id)
);

-- 후보 조회가 publish_status와 next_attempt_after로 거르고 seq로 정렬한다.
create index idx_order_events_publish on order_events (publish_status, next_attempt_after, seq);

-- 집은 묶음을 tx_id로 다시 읽는다.
create index idx_order_events_tx on order_events (tx_id);

create index idx_order_events_order on order_events (order_id);
