spring.application.name=storefront-bff
server.port=8110
management.endpoints.web.exposure.include=health,info,metrics
clients.cart.url=http://localhost:8105
clients.catalog.url=http://localhost:8102
clients.inventory.url=http://localhost:8104
clients.order.url=http://localhost:8108

storefront.cart-page.timeout=PT5S
