create table notifications (
    id         varchar(64)  primary key,
    seq        bigint       generated by default as identity,
    event_type varchar(64)  not null,
    member_id  varchar(64)  not null,
    subject    varchar(255) not null,
    body       varchar(2000) not null
);

create index idx_notifications_seq on notifications (seq);
create index idx_notifications_member_id on notifications (member_id);
