spring.application.name=api-gateway
server.port=8080
management.endpoints.web.exposure.include=health,info
clients.member.url=http://localhost:8101
clients.display.url=http://localhost:8103
clients.catalog.url=http://localhost:8102
clients.inventory.url=http://localhost:8104
clients.cart.url=http://localhost:8105
clients.order.url=http://localhost:8108
clients.shipping.url=http://localhost:8107
clients.notification.url=http://localhost:8109

