spring.application.name=catalog-service
server.port=8102
management.endpoints.web.exposure.include=health,info


spring.datasource.url=jdbc:h2:file:./.data/catalog-service
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.locations=classpath:db/migration
